### ISSUE TITLE
Got ReferenceError while running an example code

### ISSUE THREAD

**Issue by raluvy95** [TheMaestro1s/better-revolt.js#2]
Here's the output error.
```
(node:22451) UnhandledPromiseRejectionWarning: ReferenceError
    at REST.request (/home/user/Desktop/devs/js/revoltbot/node_modules/better-revolt-js/dist/rest/REST.js:40:23)
    at REST.request (/home/user/Desktop/devs/js/revoltbot/node_modules/better-revolt-js/dist/rest/REST.js:43:25)
    at REST.request (/home/user/Desktop/devs/js/revoltbot/node_modules/better-revolt-js/dist/rest/REST.js:43:25)
    at REST.request (/home/user/Desktop/devs/js/revoltbot/node_modules/better-revolt-js/dist/rest/REST.js:43:25)
    at REST.get (/home/user/Desktop/devs/js/revoltbot/node_modules/better-revolt-js/dist/rest/REST.js:66:21)
    at Client.login (/home/user/Desktop/devs/js/revoltbot/node_modules/better-revolt-js/dist/client/Client.js:28:45)
    at Object.<anonymous> (/home/user/Desktop/devs/js/revoltbot/src/index.js:5:8)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
    at processPromiseRejections (internal/process/promises.js:247:11)
    at processTicksAndRejections (internal/process/task_queues.js:96:32)
```
and I have no idea how to fix it because there's no documentation or wiki.
OS: Linux
Node.js: v14.17.5
better-revolt.js: v0.1.0-beta

**Comment by abdulrahman1s** [comment]
Can you show more information.. such as your code file?

**Comment by raluvy95** [comment]
```js
const { Client } = require('better-revolt-js')

const client = new Client()

client.login("TOKEN")

// Or using session
// client.login({ id: process.env.SESSION_ID, token: process.env.SESSION_TOKEN })

client.on('ready', () => {
    console.log('Connected')
    console.log(client.user.username)
})

client.on('message', msg => {
    if (msg.content === '!ping') {
        msg.reply('Pong!')
    }
})
```
The token is valid. I'm not sure why it's happening

**Comment by raluvy95** [comment]
After some trial and errors, I just discovered that my Node.js version is too old.
Here's the modified code in `REST.js`
```js
        try {
            res = await request.execute({ timeout: this.options.timeout });
        }
        catch (error) {
            console.error(error)
            process.exit(1)
            //if (request.retries === this.options.retries) {
            //    throw new HTTPError_1.HTTPError(error.statusText, error.constructor.name, error.status, request);
            //}
            //request.retries++;
            //return this.request(request);
        }
```
The error says `ReferenceError: AbortController is not defined`, but AbortController was added to Node.js 15.0.0
Sadly that next LTS will be in Octomber and most users uses node 14 LTS.
Can you please add the version requirements in package.json ([how?](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json#29349773)) or remove it untill next LTS?

**Comment by abdulrahman1s** [comment]
> Can you please add the version requirements in package.json ([how?](https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json#29349773)) or remove it untill next LTS?

Already [added](https://github.com/TheMaestro1s/better-revolt.js/blob/9737e06398989afb96444b21328cc62f3b08fc33/package.json#L50).
