### ISSUE TITLE
Unprocessable Entity error upon starting. 

### ISSUE THREAD

**Issue by Ne-k** [TheMaestro1s/better-revolt.js#4]
Upon starting the application, a Unprocessable Entity error emits:

```
/root/root/Revolt/node_modules/better-revolt-js/dist/rest/REST.js:63
        throw new HTTPError_1.HTTPError(res.statusText, res.constructor.name, res.status, request);
              ^

Response: Unprocessable Entity
    at REST.request (/root/root/Revolt/node_modules/better-revolt-js/dist/rest/REST.js:63:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client.login (/root/root/Revolt/node_modules/better-revolt-js/dist/client/Client.js:40:28) {
  code: 422,
  method: 'POST',
  path: 'https://api.revolt.chat/auth/login',
  info: { retries: 0, body: {} }
}
```

And the code was:

```
const { Client } = require('better-revolt.js')

const client = new Client()

client.login({token: process,env.token})

client.on('ready', () => {
    console.log('Connected')
    console.log(client.user.username)
})

client.on('message', msg => {
    if (msg.content === '!ping') {
        msg.reply('Pong!')
    }
})
```

**Comment by abdulrahman1s** [comment]
As I see your code is invalid at `client.login({token: process,env.token})`
Please follow the example exactly:

```ts
const { Client } = require('better-revolt.js')

const client = new Client()

// Login with bot account
client.login(process.env.TOKEN) // Or just put your token directly "client.login("YOUR_TOKEN_HERE")"

// Self bot
// client.login({
//    type: 'user', // user or bot
//    token: process.env.TOKEN
// })


client.on('ready', () => {
    console.log('Connected')
    console.log(client.user.username)
})

client.on('message', msg => {
    if (msg.content === '!ping') {
        msg.reply('Pong!')
    }
})
```

And make sure to update to the latest version by typeing `npm i better-revolt-js@latest`
